### ISSUE TITLE
open dev on brower

### ISSUE THREAD

**Issue by PengTanguo** [Bin-Huang/chatbox#1516]
ERROR
Cannot read properties of undefined (reading 'invoke')
TypeError: Cannot read properties of undefined (reading 'invoke')
    at DesktopPlatform.getLocale (http://localhost:1212/renderer.dev.js:178674:39)
    at http://localhost:1212/renderer.dev.js:176051:99
    at http://localhost:1212/renderer.dev.js:176056:15
ERROR
Cannot read properties of undefined (reading 'invoke')
TypeError: Cannot read properties of undefined (reading 'invoke')
    at DesktopPlatform.getLocale (http://localhost:1212/renderer.dev.js:178674:39)
    at http://localhost:1212/renderer.dev.js:176051:99
    at http://localhost:1212/renderer.dev.js:176056:15

**Comment by rba100** [comment]
I have the same issue. More details:
- platform: Windows
- `Cannot read properties of undefined (reading 'onSystemThemeChange')` Does this function exist on all platforms?
- Call stack (1 of 19 places):
```
TypeError
Cannot read properties of undefined (reading 'invoke')
Call Stack
 DesktopPlatform.getLocale
  renderer.dev.js:178719:39
 undefined
  renderer.dev.js:176051:99
 undefined
  renderer.dev.js:176056:15
```

**Comment by Jackysonwang** [comment]
请问怎么解决的

**Comment by huangwm999** [comment]
I have the same issue
